name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Checking formatting with black
      run: black --check $(git ls-files '*.py')

    - name: Checking typing with mypy
      run: mypy $(git ls-files '*.py')

    - name: Analysing the code with pylint
      run: pylint $(git ls-files '*.py')
