name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint

    - name: Checking formatting with black
      run: black --check .

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
