name: Code Quality Check

on: [push]

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: pip install -r requirements-ci.txt

    - name: Check formatting with black
      run: black --check .

    - name: Check typing with mypy
      run: mypy src tests

    - name: Check code with pylint
      run: pylint src tests

    - name: Run tests with coverage
      run: |
        coverage run -m unittest
        coverage report --fail-under=80
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov
